import time
import random
print("Welcome to Biff's Revenge")
time.sleep(1)
input("Press Enter to Start")
print("You are a fish named Biff. You live in a fish tank with about 10 other Betta fish. Your job is to gather food and bring it back to the village of Betta fish. One day while you are going to gather food you find that there is a mysterious glowing object. The object looks nothing like anything you had ever seen before.")
time.sleep(5)
print("Suddenly a fish swam out of the otherworldly object. The fish was not from your village, because the mark of your village is blue fish, and this fish was red.")
time.sleep(5)
print("You went about your day normally collecting food for the village like your daily routine.")
time.sleep(5)
print("You go back to your village to find only ruins and that same red fish you saw earlier.")
time.sleep(5)
print("The fish begins to attack you.")
biff_health = 10
enemy_health = 5
while biff_health > 0 and enemy_health > 0:
    user = input("Attack, Heal, or special attack?").lower()
    print("""><((((o>
          
                            <o))))))><""")
    
    print("Biff HP=")
    print(biff_health)
    if user == "attack":
        print("Biff attacks.")
        print("""        
                        
               ><((((@> <o))))))><""")
        enemy_health -= random.randint(1, 2)
        time.sleep(1)
        print("Enemy HP=")
        print(enemy_health)
    elif user == "heal":
        if biff_health >= 10:
            print("Already Full Health")
            continue
        print("Biff Heals")
        print("""><((((o>
          
                                                             <o))))))><""")
        biff_health += 1
        time.sleep(1)
        print("Biff HP=")
        print(biff_health)
    elif user == "special attack":
        print("Biff does a risky special attack")
        print("""        
                        
               ><((((@> <o))))))><""")
        damage = random.randint(0, 5)
        enemy_health -= damage
        time.sleep(1)
        print("Enemy HP=")
        print(enemy_health)
        if damage == 0:
            print("Biff Hurt himself")
            biff_health -= random.randint(0, 5)
    if enemy_health > 0:
        print("The Red Fish Attacks")
        biff_health -= random.randint(1, 2)
        print("Biff HP=")
        print(biff_health)
    if enemy_health <= 0:
        print("You defeated the enemy fish")
        time.sleep(2)
        print("Biff Leveled Up")
        print("Level 1 -> Level 2")
        print("><(((((o>")
        print("--10 HP to 15HP")
        print("--Attack Damage 1, or 2 --> 2, or 3")
        print("--Heal 1HP -> 2HP")
        print("HP")
        print("<##########>")
        time.sleep(.8)
        print("<###########>")
        time.sleep(.8)
        print("<############>")
        time.sleep(.8)
        print("<#############>")
        time.sleep(.8)
        print("<##############>")
        time.sleep(.8)
        print("<###############>")
if biff_health <= 0:
    print("Game Over")
    time.sleep(2)
    exit()
time.sleep(2)
print("You realize that the red fish was the one who destroyed you village. After defeating the red fish you realize that there are more")
time.sleep(4)
print("Many more...")
time.sleep(4)
print("The army of red fish chase you through the mysterious object. Fighting with everything you had you tried not to go through it.")
time.sleep(2)
print("But, you fell on you face and bounced off of the ground into the portal...")
time.sleep(3)
print("You find yourself in a strange place. You are in a huge fish tank, but everything is different.")
time.sleep(2)
print("No matter where you look you cannot see the glass. You franticly search around to find any signs of your village.")
time.sleep(2)
print("In the middle of searching you get teleported to another place.")
time.sleep(2)
print("You see tons of sand and many sea creatures.")
time.sleep(2)
print("You come across another enemy.")
time.sleep(1)
print("The enemy is an octopus.")
time.sleep(1)
print("The octopus attacks")
biff_health = 15
enemy_health = 20
while biff_health > 0 and enemy_health > 0:
    user = input("Attack, Heal, or special attack?").lower()
    print("""><((((o>
                             (. .)
                            (((())))""")
    
    print("Biff HP=")
    print(biff_health)
    if user == "attack":
        print("Biff attacks.")
        print("""        
                         (. .) 
               ><((((@> (((())))""")
        enemy_health -= random.randint(2, 3)
        time.sleep(1)
        print("Enemy HP=")
        print(enemy_health)
    elif user == "heal":
        if biff_health >= 15:
            print("Already Full Health")
            continue
        print("Biff Heals")
        print("""><((((o>
                                                              (. .)
                                                             (((())))""")
        biff_health += 2
        time.sleep(1)
        print("Biff HP=")
        print(biff_health)
    elif user == "special attack":
        print("Biff does a risky special attack")
        print("""        
                         (. .)
               ><((((@> (((())))""")
        damage = random.randint(0, 5)
        enemy_health -= damage
        time.sleep(1)
        print("Enemy HP=")
        print(enemy_health)
        if damage == 0:
            print("Biff Hurt himself")
            biff_health -= random.randint(0, 5)
    if enemy_health > 0:
        print("The octopus attacks")
        biff_health -= random.randint(2, 3)
        print("Biff HP=")
        print(biff_health)
    if enemy_health <=0:
        print("You defeated the octopus")
        print("""  (x x)
                  (((())))""")
        print("The octopus has injured you")
    if biff_health <=0:
        print("Game Over")
        time.sleep(2)
        exit()
print("Biff is now halfway to level 3")
time.sleep(2)
print("><((((@>")
time.sleep(2)
print("Upon further inspection of the octopus you realize that it was red like the fish.")
time.sleep(1.5)
input("...")
print("You now find out that you are in the ocean.")
time.sleep(1.5)
print("It was exactly like how fish from your clan had described it.")
print("You decided to dig in the sand.")
time.sleep(2)
print("When you started digging you went imediatly to the bottom it was still the ocean, but it was floating over some kind of dimension, planet, universe, rock thing.")
time.sleep(2)
print("You decide that you must figure out what it is.")
time.sleep(2)
print("You realize it was were all of the red fish come from.")
time.sleep(2)
print("You notice thousands of these fish building something.")
time.sleep(2)
print("Something Evil,")
time.sleep(2)
print("Something sinister")
time.sleep(2)
print("A portal to send their red fish to take control of your kingdom.")
time.sleep(2)
print("You finnaly realize why they tried to attack you.")
print("You realize that you should not venture through the strange place and that you must defend your home.")
print("But how should oneself get down there?")
time.sleep(2)
print("Suddenly a giant fish roughly ten times the size of the octopus attacks you!")
time.sleep(2)
print("You swiftly dodge, and he hits the bottom the very bottom of the ocean broke!")
time.sleep(2)
print("All the sea creatures and water were gettting sucked through the broken sea floor landing on the strange object.")
time.sleep(2)
print("For some reason every sea creature dissapeared, upon hitting the new place.")
time.sleep(2)
print("It teleported you to another dimension where there were these strange hands that reached from above and gravved you.")
time.sleep(1)
print("Which then telepoted you back to the strange dimension beneath the ocean.")
time.sleep(2)
print("This kept happening for about an hour.")
time.sleep(2)
print("Finnaly when it stopped you were stuck in the strange dimension.")
time.sleep(2)
print("It was too late the invaders went through the portal and into your dimension.")
time.sleep(2)
print("Game Over")
time.sleep(10)
print("Why are you still here? The game is over.")
time.sleep(2)
print("Do you not understand it is over you lost and the enemy fish won.")
time.sleep(5)
print("Why do you still persist!?")
time.sleep(2)
print("Are you looking for a fulfilling ending?")
time.sleep(2)
print("Well you are not going to get one.")
time.sleep(2)
print("Alright if it will make you go away then I will make a happy ending.")
time.sleep(2)
print("You and all the red fish lived happily ever after.")
time.sleep(2)
print("You are still not content!?")
time.sleep(2)
print("You know that not every videogame has a happy ending right!?")
time.sleep(2)
print("Okay okay I give up!")
print("I'll give you one more battle.")
time.sleep(2)
print("The mighty hands from above dropped a weird spear like object made of wood that was pointy on both ends.")
time.sleep(2)
print("It had some food from a humans mouth on it.")
time.sleep(2)
print("You picked up the toothpick instantly giving you and upgrade to level 5")
print("Level 2 -> 5")
print("><(((((((((@>")
time.sleep(2)
print("--HP 15 -> 100")
time.sleep(2)
print("--Attack Damage 1, 2, 3 -> 50")
time.sleep(2)
print("--Healing 1, or 2 -> 20")
time.sleep(2)
print("You are now the maximum level.")
time.sleep(2)
print("Well now there is only one thing left to do.")
time.sleep(2)
print("Swim around in circles!")
time.sleep(5)
print("And take back your home.")
time.sleep(2)
print("You head through the portal and get ready to fight the fish.")
time.sleep(2)
print("With your new level and toothpick you fight you way through the waves of enemies vanquishing half of the army. The rest fear you now seeing your newfound power you decide to allow them to escape on one condition.")
time.sleep(2)
print("They tell you were the rest of yoour village is.")
time.sleep(2)
print("And just like that Biff got all of his clan members back and his home.")
time.sleep(10)
print("Alright are you satified now!?")
time.sleep(2)
print("Either Way the game is over now.")
time.sleep(5)
exit()